### ISSUE TITLE
ASPNET CORE 3.1 c# client generation Error - Multiple Actions Not Generated

### ISSUE THREAD

**Issue by cetindogu** [zijianhuang/webapiclientgen#101]
Web Api Controller Methods   with [HttpPost] or [HttpGet] is OK. it's client code generated.
BUT
Web Api Controller Methods   with [HttpGet,HttpPost]   c# Client not generated. two HttpGet generated

i tried
[HttpGet]
[HttpPost]   two lines. BUT same ERROR;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type '...' already defines a member called '...' with the same parameter types	...	C:\Users\....ClientApi\WebApiClientAuto.cs

**Comment by zijianhuang** [comment]
little info to follow up.

is this related to issue #102?

**Comment by zijianhuang** [comment]
not enough info and no response.
