### ISSUE TITLE
The WebAPI code generator doesn't appear to run under VS 2022

### ISSUE THREAD

**Issue by KeithVinson** [zijianhuang/webapiclientgen#129]
Hi Zijian, 
I tried to run the code gen controller for one of my projects under VS 2022. It appears to run without throwing an exception but it fails to generate (or update) the WebAPIClientAuto.cs file. I went back to VS2019 and it ran as expected. Are you aware of any difference between VS2019 & VS 2022 as it relates to the Web API Code generator?

Just thought you might like to know.

Keith

**Comment by zijianhuang** [comment]
I have been using it all the time with VS 2022 since day 1 of VS 2022. Have you check your .NET Runtime/SDK versions?
In the Main branch, currently it is with .NET 7.

On my dev PC NET 7.0.4 is installed.

**Comment by KeithVinson** [comment]
Thanks, I will check that out. When I figure out what is off with my install of VS 2022 I will post my results here, so if anyone else has a similar issue, hopefully they will find this thread.

Cheers

**Comment by zijianhuang** [comment]
no news is good news
