### ISSUE TITLE
Generate Client For ASP.Net Core Web API

### ISSUE THREAD

**Issue by pranaykothari** [zijianhuang/webapiclientgen#14]
Tried to use clientgen with asp.net core 1.1 and Angular 4 projects, but nuget package installation does not generate the controller file. Even copied this file from github into the controllers folder, and then created the config json as suggested, but throws a compile time error (for Configuration.Services.GetApiExplorer()). 

Can you suggest please?

Thanks,
Pranay.

**Comment by zijianhuang** [comment]
not yet supported core. issue #2 is for core which was called vNext a few years ago.

**Comment by zijianhuang** [comment]
according to https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server and  https://github.com/aspnet/Home/issues/1281,

webapiclientgen will not be supporting core, for good reasons.
