### ISSUE TITLE
Investigate possible bugs in System.Text.Json.JsonSerializer or ASP.NET binding when dealing with uint128 and BigInteger.

### ISSUE THREAD

**Issue by zijianhuang** [zijianhuang/webapiclientgen#151]
I am 95% sure JsonSerializer  was able to deal with this type a few versions before.

Need to check out some old tags to find out which .NET version could cause the problem. .NET 6 is probably the starting point.

**Comment by zijianhuang** [comment]
Newtonsoft.Json can parse payload of numbers with  (string object in JS) or without double quotes (number object in JS).
while System.Text.Json can parse only the ones without double quotes.

To make both C# clients and JS clients happy for large integral numbers, using Newtonsoft.Json is still the only way.

**Comment by ZijianFLG** [comment]
no problem at all. Improved the test suites and the demo apps. ready to close
