### ISSUE TITLE
utilize HttpClientJsonExtensions.GetFromJsonAsync and alike

### ISSUE THREAD

**Issue by ZijianFLG** [zijianhuang/webapiclientgen#160]
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.getfromjsonasync

[HttpClientJsonExtensions](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions)

since the primary support has been shifted from newtonsoft.json to system.text.json, it may be a good time to utilize this extensions to make the generated codes even shorter.

**Comment by zijianhuang** [comment]
Not to do it because I need to support custom request headers manipulation.
