### ISSUE TITLE
Generate a component for angular 6, 7

### ISSUE THREAD

**Issue by weedkiller** [zijianhuang/webapiclientgen#69]
Hi can this generate a component for Angular 6 or 7.

By that I mean, can it generate the 3 files needed in a component , `Service`,  `HTML `and Component?

**Comment by zijianhuang** [comment]
You use the generated client API as service, as shown in the Angular demo included in this project, as well as in the other 2 dedicated demo repros listed in readme.md.

**Comment by zijianhuang** [comment]
no action needed
