### ISSUE TITLE
Error in webapiclientgencore for NG

### ISSUE THREAD

**Issue by alainjlavoie** [zijianhuang/webapiclientgen#83]
Using VS2019, core 3.1.1
Hi, I keep getting this error when executing:
CodeGen.GenerateClientAPIs(this.webRootPath, settings, apiDescriptions);

"StartIndex cannot be less than zero. (Parameter 'startIndex')"

I noticed that hostingEnvironment.WebRootPath is null when I run it in debug but I get the error when hitting the controller running in a .exe as well.

I am trying to generate an Angular2 client.  Here's the config:

{
  "ApiSelections": {
    "DataModelAssemblyNames": [
      "xxxx.Application"
    ],
    "CherryPickingMethods": 4
  },

  "ClientApiOutputs": {
    "CamelCase": false,

    "Plugins": [
      {
        "AssemblyName": "Fonlow.WebApiClientGenCore.NG2",
        "TargetDir": "..\\..\\..\\..\\xxx.Presentation\\src\\ClientApi",
        "TSFile": "xxxClientApi.ts",
        "AsModule": true,
        "ContentType": "application/json;charset=UTF-8"
      }

    ]
  }
}

Any idea?

**Comment by zijianhuang** [comment]
which version of webapiclientgencore ?

Have you tried the latest? 3.5.2

**Comment by zijianhuang** [comment]
no reponse from op.
